### PR TITLE
add ghost row

### PR DESCRIPTION
**Pull request by ivbrajkovic**
**Description**

This PR introduces a solution to style a hover image that appears when dragging an element in one of my projects. The native drag-and-drop API does not provide built-in styling capabilities, so this implementation provides a simple solution to address this requirement.

**Changes Made**

- Added a GhostRow class that handles the creation and manipulation of the ghost row element used for styling during drag-and-drop.
- Implemented the create method to create a clone of the original row element and apply specified styles and classes.
- Implemented the move method to update the position of the ghost row element based on the mouse cursor's position.
- Added support for customizing row and cell styles through the rowStyle and cellStyle props.
- Introduced the rowStylesToClone and cellStylesToClone props to allow specifying additional CSS properties to be cloned from the original row and cell elements.
- Handled the case of Firefox not firing mousemove events during drag by adding a workaround using the dragover event.
- Handled cleanup in the remove method to remove the ghost row element and unregister event listeners.

These changes enable the desired styling of the hover element during drag-and-drop operations by providing an easy-to-use and customizable solution.

### CODE REVIEW

**Comment by KevinVandy** [comment]
Hey so I appreciate the work you put into this, but I do not think this is worth adding to the core of MRT. It introduces a lot of complexity and extra apis just for a very small effect. I think you should still be able to implement this in your own project by overriding some cell and component renders though.

**Comment by ivbrajkovic** [comment]
l dont see how I could implement this effect overriding a cell. Can you give me an example? I really need these effects because the tables are very bright, and the native ghost image doesn't display very well.

**Comment by KevinVandy** [comment]
@ivbrajkovic You should be able to do something like this using the `displayColumnDefOptions` table option/prop

```jsx
displayColumnDefOptions: {
  'mrt-drag-row': {
    Cell: ({ cell, table }) => <YouCustomDragHandleComponent cell={cell} table={table} />
  }
}
```

Where you put the code you would want to be in the drag handle component in this custom `Cell` render

**Comment by ivbrajkovic** [comment]
Thanks l’ll try 🙂

**Comment by KevinVandy** [comment]
wait this might not work because of the way I have this coded just for the drag handle component. This would work for all other display columns. Might refactor this real quick

**Comment by ivbrajkovic** [comment]
I neew a ref to row been draged and onDrag, onDragStared and OnDragEnd and i can implement GhostRow on client :)

**Comment by KevinVandy** [comment]
yeah, was just adding that now

image

**Comment by KevinVandy** [comment]
@ivbrajkovic https://github.com/KevinVandy/mantine-react-table/releases/tag/v1.0.0-beta.21

**Comment by ivbrajkovic** [comment]
Hi, can you please add possibility to customize draggingBorders?

**Pull request closed without merging**
