### PR TITLE
feat: updated to Mantine v7.8

### PR DESCRIPTION
**Pull request by alessandrojcm**
Updated package and examples to Mantine 7.8

### CODE REVIEW

**Comment by denihs** [comment]
Will it take too long for this to be released? :grimacing:

**Comment by alessandrojcm** [comment]
> Will it take too long for this to be released? 😬

Waiting for @KevinVandy approval.

**Comment by danikane** [comment]
There's 7.9 now ...

**Comment by alessandrojcm** [comment]
> There's 7.9 now ...

Yep I'm away, will update when I get a chance.

**Comment by alessandrojcm** [comment]
Closing this in favour if #323

**Pull request closed without merging**
