### PR TITLE
fix: 'reset' was not being passed to getDefaultColumnOrderIds

### LINKED ISSUE #384: Reset order button is not working (v2)
### mantine-react-table version

2.0.0-beta

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I encountered it locally but it can be repeated on the documentation page. After changing the column order, you can see that the "Reset Order" button does not work
https://v2.mantine-react-table.com/docs/guides/column-ordering-dnd

### Minimal, Reproducible Example - (Optional, but Recommended)

https://v2.mantine-react-table.com/docs/guides/column-ordering-dnd

### Screenshots or Videos (Optional)

_No response_

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

### PR DESCRIPTION
**Pull request by alessandrojcm**
Closes #384

### CODE REVIEW

**Comment by KevinVandy** [comment]
This potentially isn't necessarily what we want. I think this sets the state as an empty array

**Comment by DKGH** [comment]
Is this fixed? What version do I need for this?

**Comment by KevinVandy** [comment]
I'm not sure the proposed change is the fix. We may want to call our internal getDefaultColumnOrder until instead.

**Comment by alessandrojcm** [comment]
> getDefaultColumnOrder un

So is the callback meant  to call getDefaultColumnOrder instead of getDefaultColumnOrderIds? What is the expected result when you click the reset button?

**Comment by KevinVandy** [comment]
I'll test this more thoroughly tonight

**Review by KevinVandy — APPROVED** [review]

**Pull request merged**
